# Generated by Django 5.0.1 on 2024-02-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='song_pictures/')),
                ('file', models.FileField(upload_to='song_files/')),
            ],
        ),
    ]
