# Generated by Django 5.0.1 on 2024-02-10 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
