# Generated by Django 5.0.1 on 2024-02-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
    ]
