# Generated by Django 5.0.1 on 2024-02-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_created_at_song_genre_song_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=255),
        ),
    ]
