# Generated by Django 5.0.1 on 2024-02-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Playlist',
            field=models.ManyToManyField(blank=True, related_name='playlist_songs', to='songs.playlist'),
        ),
    ]
