# Generated by Django 5.0.1 on 2024-02-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_song_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Playlist',
        ),
        migrations.AddField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='songs_in_playlists', to='songs.playlist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists_in_songs', to='songs.song'),
        ),
    ]
