# Generated by Django 5.0.1 on 2024-03-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_remove_song_playlists_alter_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(related_name='playlist_on_songs', to='songs.playlist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='songs_on_playlists', to='songs.song'),
        ),
    ]
