# Generated by Django 5.0.1 on 2024-03-01 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_song_playlist_alter_playlist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_on_songs', to='songs.playlist'),
            preserve_default=False,
        ),
    ]
