# Generated by Django 5.0.1 on 2024-01-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_email_verified_emailconfirmationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.DeleteModel(
            name='EmailConfirmationToken',
        ),
    ]
