# Generated by Django 5.0.1 on 2024-02-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_likedsong_song_likedsong_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedsong',
            old_name='song',
            new_name='songs',
        ),
    ]
