# Generated by Django 5.0.1 on 2024-02-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profile_font'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedSong',
        ),
    ]
