# Generated by Django 5.0.1 on 2024-02-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_contact_contact_remove_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='comment',
            new_name='message',
        ),
    ]
