# Generated by Django 5.0.1 on 2024-02-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_rename_comment_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
