# Generated by Django 5.0.1 on 2024-02-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_artistregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
