# Generated by Django 5.0.1 on 2024-02-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_user_is_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistregister',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
