# Generated by Django 5.0.1 on 2024-03-18 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_artistregister_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistregister',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='artistregister',
            name='email',
        ),
        migrations.RemoveField(
            model_name='artistregister',
            name='name',
        ),
        migrations.AddField(
            model_name='artistregister',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
