# Generated by Django 5.0.1 on 2024-03-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_artistregister_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistregister',
            name='verification_token',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
