# Generated by Django 5.0.1 on 2024-03-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_user_is_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscriber',
        ),
    ]
