# Generated by Django 5.0.1 on 2024-03-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_subscribers_plan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_superuser',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
