# Generated by Django 4.2.8 on 2024-03-24 13:22

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_rename_is_admin_user_is_superuser_delete_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=colorfield.fields.ColorField(default='#1C295E', image_field=None, max_length=25, samples=None),
        ),
    ]
