export const ADS_LIST_REQUEST = 'ADS_LIST_REQUEST';
export const ADS_LIST_SUCCESS = 'ADS_LIST_SUCCESS';
export const ADS_LIST_FAILURE = 'ADS_LIST_FAILURE';

export const UPLOAD_AD_REQUEST = 'UPLOAD_AD_REQUEST';
export const UPLOAD_AD_SUCCESS = 'UPLOAD_AD_SUCCESS';
export const UPLOAD_AD_FAILURE = 'UPLOAD_AD_FAILURE';

export const GET_AD_REQUEST = 'GET_AD_REQUEST';
export const GET_AD_SUCCESS = 'GET_AD_SUCCESS';
export const GET_AD_FAILURE = 'GET_AD_FAILURE';

export const EDIT_AD_REQUEST = 'EDIT_AD_REQUEST';
export const EDIT_AD_SUCCESS = 'EDIT_AD_SUCCESS';
export const EDIT_AD_FAILURE = 'EDIT_AD_FAILURE';

export const DELETE_AD_REQUEST = 'DELETE_AD_REQUEST';
export const DELETE_AD_SUCCESS = 'DELETE_AD_SUCCESS';
export const DELETE_AD_FAILURE = 'DELETE_AD_FAILURE';
