
export const SONG_LIST_REQUEST = 'SONG_LIST_REQUEST';
export const SONG_LIST_SUCCESS = 'SONG_LIST_SUCCESS';
export const SONG_LIST_FAILURE = 'SONG_LIST_FAILURE';

export const SONG_LIKE_REQUEST = 'SONG_LIKE_REQUEST';
export const SONG_LIKE_SUCCESS = 'SONG_LIKE_SUCCESS';
export const SONG_LIKE_FAILURE = 'SONG_LIKE_FAILURE';
export const SONG_UNLIKE_REQUEST = 'SONG_UNLIKE_REQUEST';
export const SONG_UNLIKE_SUCCESS = 'SONG_UNLIKE_SUCCESS';
export const SONG_UNLIKE_FAILURE = 'SONG_UNLIKE_FAILURE';


/* export const ADD_SONG = 'ADD_SONG';
export const DELETE_SONG = 'DELETE_SONG';
export const UPDATE_SONG = 'UPDATE_SONG'; */

