export const SONG_LIST_REQUEST = 'SONG_LIST_REQUEST';
export const SONG_LIST_SUCCESS = 'SONG_LIST_SUCCESS';
export const SONG_LIST_FAILURE = 'SONG_LIST_FAILURE';


export const SONG_DETAILS_REQUEST = 'SONG_DETAILS_REQUEST';
export const SONG_DETAILS_SUCCESS = 'SONG_DETAILS_SUCCESS';
export const SONG_DETAILS_FAILURE = 'SONG_DETAILS_FAILURE';

export const SONG_EDIT_REQUEST = 'SONG_EDIT_REQUEST';
export const SONG_EDIT_SUCCESS = 'SONG_EDIT_SUCCESS';
export const SONG_EDIT_FAILURE = 'SONG_EDIT_FAILURE';

export const SONG_ADD_REQUEST = 'SONG_ADD_REQUEST';
export const SONG_ADD_SUCCESS = 'SONG_ADD_SUCCESS';
export const SONG_ADD_FAILURE = 'SONG_ADD_FAILURE';

export const SONG_DELETE_REQUEST = 'SONG_DELETE_REQUEST';
export const SONG_DELETE_SUCCESS = 'SONG_DELETE_SUCCESS';
export const SONG_DELETE_FAILURE = 'SONG_DELETE_FAILURE';

export const LIKE_SONG_REQUEST = 'LIKE_SONG_REQUEST';
export const LIKE_SONG_SUCCESS = 'LIKE_SONG_SUCCESS';
export const LIKE_SONG_FAILURE = 'LIKE_SONG_FAILURE';

export const FETCH_LIKED_SONGS_REQUEST = 'FETCH_LIKED_SONGS_REQUEST';
export const FETCH_LIKED_SONGS_SUCCESS = 'FETCH_LIKED_SONGS_SUCCESS';
export const FETCH_LIKED_SONGS_FAILURE = 'FETCH_LIKED_SONGS_FAILURE';