export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_SEND_CHANGE_PASSWORD_REQUEST = 'USER_SEND_CHANGE_PASSWORD_REQUEST';
export const USER_SEND_CHANGE_PASSWORD_SUCCESS = 'USER_SEND_CHANGE_PASSWORD_SUCCESS';
export const USER_SEND_CHANGE_PASSWORD_FAIL = 'USER_SEND_CHANGE_PASSWORD_FAIL';
export const USER_CONFIRM_CHANGE_PASSWORD_RESET = 'USER_CONFIRM_CHANGE_PASSWORD_RESET';
export const USER_CONFIRM_CHANGE_PASSWORD_REQUEST = 'USER_CONFIRM_CHANGE_PASSWORD_REQUEST';
export const USER_CONFIRM_CHANGE_PASSWORD_SUCCESS = 'USER_CONFIRM_CHANGE_PASSWORD_SUCCESS';
export const USER_CONFIRM_CHANGE_PASSWORD_FAIL = 'USER_CONFIRM_CHANGE_PASSWORD_FAIL';

export const USER_VERIFY_OTP_REQUEST = 'USER_VERIFY_OTP_REQUEST';
export const USER_VERIFY_OTP_SUCCESS = 'USER_VERIFY_OTP_SUCCESS';
export const USER_VERIFY_OTP_FAIL = 'USER_VERIFY_OTP_FAIL';

export const USER_RESEND_OTP_REQUEST = 'USER_RESEND_OTP_REQUEST';
export const USER_RESEND_OTP_SUCCESS = 'USER_RESEND_OTP_SUCCESS';
export const USER_RESEND_OTP_FAIL = 'USER_RESEND_OTP_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_CONTACT_US_REQUEST = 'USER_CONTACT_US_REQUEST';
export const USER_CONTACT_US_SUCCESS = 'USER_CONTACT_US_SUCCESS';
export const USER_CONTACT_US_FAIL = 'USER_CONTACT_US_FAIL';

export const ARTIST_REGISTER_REQUEST = 'ARTIST_REGISTER_REQUEST';
export const ARTIST_REGISTER_SUCCESS = 'ARTIST_REGISTER_SUCCESS';
export const ARTIST_REGISTER_FAILURE = 'ARTIST_REGISTER_FAILURE';

export const ARTIST_VERIFY_REQUEST = 'ARTIST_VERIFY_REQUEST';
export const ARTIST_VERIFY_SUCCESS = 'ARTIST_VERIFY_SUCCESS';
export const ARTIST_VERIFY_FAILURE = 'ARTIST_VERIFY_FAILURE';

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

export const USER_UPDATE_SUBSCRIBER_REQUEST = 'USER_UPDATE_SUBSCRIBER_REQUEST';
export const USER_UPDATE_SUBSCRIBER_SUCCESS = 'USER_UPDATE_SUBSCRIBER_SUCCESS';
export const USER_UPDATE_SUBSCRIBER_FAIL = 'USER_UPDATE_SUBSCRIBER_FAIL'

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';