export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_SEND_CHANGE_PASSWORD_REQUEST = 'USER_SEND_CHANGE_PASSWORD_REQUEST';
export const USER_SEND_CHANGE_PASSWORD_SUCCESS = 'USER_SEND_CHANGE_PASSWORD_SUCCESS';
export const USER_SEND_CHANGE_PASSWORD_FAIL = 'USER_SEND_CHANGE_PASSWORD_FAIL';
export const USER_CONFIRM_CHANGE_PASSWORD_RESET = 'USER_CONFIRM_CHANGE_PASSWORD_RESET';
export const USER_CONFIRM_CHANGE_PASSWORD_REQUEST = 'USER_CONFIRM_CHANGE_PASSWORD_REQUEST';
export const USER_CONFIRM_CHANGE_PASSWORD_SUCCESS = 'USER_CONFIRM_CHANGE_PASSWORD_SUCCESS';
export const USER_CONFIRM_CHANGE_PASSWORD_FAIL = 'USER_CONFIRM_CHANGE_PASSWORD_FAIL';

export const USER_VERIFY_OTP_REQUEST = 'USER_VERIFY_OTP_REQUEST';
export const USER_VERIFY_OTP_SUCCESS = 'USER_VERIFY_OTP_SUCCESS';
export const USER_VERIFY_OTP_FAIL = 'USER_VERIFY_OTP_FAIL';

export const USER_RESEND_OTP_REQUEST = 'USER_RESEND_OTP_REQUEST';
export const USER_RESEND_OTP_SUCCESS = 'USER_RESEND_OTP_SUCCESS';
export const USER_RESEND_OTP_FAIL = 'USER_RESEND_OTP_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const FETCH_LIKED_SONGS_REQUEST = 'FETCH_LIKED_SONGS_REQUEST';
export const FETCH_LIKED_SONGS_SUCCESS = 'FETCH_LIKED_SONGS_SUCCESS';
export const FETCH_LIKED_SONGS_FAIL = 'FETCH_LIKED_SONGS_FAIL';
export const ADD_LIKED_SONG_REQUEST = 'ADD_LIKED_SONG_REQUEST';
export const ADD_LIKED_SONG_SUCCESS = 'ADD_LIKED_SONG_SUCCESS';
export const ADD_LIKED_SONG_FAILURE = 'ADD_LIKED_SONG_FAILURE';
export const MATCHED_SONGS_REQUEST = 'MATCHED_SONGS_REQUEST';
export const MATCHED_SONGS_SUCCESS = 'MATCHED_SONGS_SUCCESS';
export const MATCHED_SONGS_FAIL = 'MATCHED_SONGS_FAIL';