export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_SEND_CHANGE_PASSWORD_REQUEST = 'USER_SEND_CHANGE_PASSWORD_REQUEST';
export const USER_SEND_CHANGE_PASSWORD_SUCCESS = 'USER_SEND_CHANGE_PASSWORD_SUCCESS';
export const USER_SEND_CHANGE_PASSWORD_FAIL = 'USER_SEND_CHANGE_PASSWORD_FAIL';
export const USER_CONFIRM_CHANGE_PASSWORD_RESET = 'USER_CONFIRM_CHANGE_PASSWORD_RESET';
export const USER_CONFIRM_CHANGE_PASSWORD_REQUEST = 'USER_CONFIRM_CHANGE_PASSWORD_REQUEST';
export const USER_CONFIRM_CHANGE_PASSWORD_SUCCESS = 'USER_CONFIRM_CHANGE_PASSWORD_SUCCESS';
export const USER_CONFIRM_CHANGE_PASSWORD_FAIL = 'USER_CONFIRM_CHANGE_PASSWORD_FAIL';

export const USER_VERIFY_OTP_REQUEST = 'USER_VERIFY_OTP_REQUEST';
export const USER_VERIFY_OTP_SUCCESS = 'USER_VERIFY_OTP_SUCCESS';
export const USER_VERIFY_OTP_FAIL = 'USER_VERIFY_OTP_FAIL';